### ISSUE TITLE
Failed to include TinyMAT as a CMake project

### ISSUE THREAD

**Issue by songyuncen** [jkriege2/TinyMAT#3]
CMake Error at MyProject/3rdparty/TinyMAT/src/CMakeLists.txt:161 (configure_file):
  configure_file Problem configuring file.

The directory of the "readme.txt.in" written in line 161 of the CMakeLists.txt is ${CMAKE_SOURCE_DIR} which is my project's top-level directory. I think the CMAKE_SOURCE_DIR should probably be replaced with PROJECT_SOURCE_DIR.

**Comment by jkriege2** [comment]
Hi!

I merged your PR, which should solve this issue.

Best & Thanks,
JAN
